### ISSUE TITLE
Not working at CentOS 7

### ISSUE THREAD

**Issue by robertofelix** [ImDevinC/wc-watcher#1]
![image](https://user-images.githubusercontent.com/20323666/41244832-4bd90a82-6d74-11e8-943f-1728b1eeff0c.png)

All requirements were installed as you can see. I set up my own private.py with my Webhook. The soccerbot.py remains original. When I try to run it, I got this message:

 
![image](https://user-images.githubusercontent.com/20323666/41244814-39abf70c-6d74-11e8-9888-9f59c92dcac3.png)

Any ideas? Thanks in advance!

**Comment by ImDevinC** [comment]
The bot is built on Python3, which is probably why you're seeing that issue

**Comment by robertofelix** [comment]
Thanks for the feedback, it's working now. Let's celebrate the World Cup! :)
