### ISSUE TITLE
asyncio.ensure_future() not available on raspbian jessie with python 3.4.2

### ISSUE THREAD

**Issue by shmick** [ImDevinC/wc-watcher#10]
The calls to asyncio.ensure_future() need to be changed to asyncio.async() if running this on a raspi with raspbian jessie.

```
$ diff -i soccerbot.py.orig soccerbot.py.jessie
283c283
<     main_task = asyncio.ensure_future(loop.run_in_executor(executor, main))
---
>     main_task = asyncio.async(loop.run_in_executor(executor, main))
286c286
<         heart_beat_task = asyncio.ensure_future(loop.run_in_executor(executor, heart_beat))
---
>         heart_beat_task = asyncio.async(loop.run_in_executor(executor, heart_beat))
```

**Comment by ImDevinC** [comment]
I don't plan on fixing this since I built for python 3.6.0. You're free to make these changes locally on your branch but I don't forsee pulling them in. Coincidentally, I also ran into this issue when building, and ended up upgrading my Raspbian instance.
