### ISSUE TITLE
Substitution names swapped

### ISSUE THREAD

**Issue by BoredMind** [ImDevinC/wc-watcher#11]
<img width="417" alt="screen shot 2018-06-15 at 12 38 59 pm" src="https://user-images.githubusercontent.com/67579/41486383-24515fbe-7099-11e8-8e02-d5f9dc4dec05.png">

Aspas came on for Costa, not the other way around.  It seems to be backward.

**Comment by pip8786** [comment]
I saw the same thing on mine. Looking through the code it's picking up the right ID from the feed but maybe the feed has it swapped?

**Comment by ImDevinC** [comment]
Fixed in #13
