### ISSUE TITLE
Events stopped appearing after a while during an ongoing game

### ISSUE THREAD

**Issue by stardust20** [ImDevinC/wc-watcher#19]
The bot stopped reporting events after some time:

```
55' Yellow card.
> H C HWANG (Korea Republic)
```

After than, wc-watcher needs to be restarted to get the latests events. Checking on the debug channel, the health pings are still arriving.

**Comment by ImDevinC** [comment]
This was actually the FIFA API not updating properly. I was checking this at the same time and there was over a 15 minute delay where the API wasn't updating on their end.
