### ISSUE TITLE
Make it more obvious that "CHANNEL" config may need updating

### ISSUE THREAD

**Issue by Jack-Edwards** [ImDevinC/wc-watcher#20]
Hello, I work on the same team as @omarrodriguez15, where we do not have a ton of control over our Slack space.

By following the steps provided in the ReadMe.md (great ReadMe.md, by the way) I would have left the soccerbot to post to our space's main "random" channel.  This channel has a huge population in our space.  I would have deeply regretted leaving soccerbot configured to post to that channel.

Suggest either changing the default "CHANNEL" value in private.py to be something that would never work ("ChangeMe123") or including steps in ReadMe.md to make it obvious that "CHANNEL" might need updating in some contexts.

**Comment by ImDevinC** [comment]
Thanks for the PR to fix this
