### ISSUE TITLE
Substitutions are backwards

### ISSUE THREAD

**Issue by bgm13** [ImDevinC/wc-watcher#22]
The substitution  event seems to be backwards.
`82' Substitution for Uruguay. > C. SANCHEZ comes on for N. NANDEZ.`

Nandez came on for Sanchez, Sanchez was substituted off.

http://www.livescore.com/soccer/world-cup/group-a/uruguay-vs-saudi-arabia/1-2059524/

**Comment by BoredMind** [comment]
This was fixed in commit [a293551](https://github.com/ImDevinC/wc-watcher/commit/21bc7b5d54d6d9990d5f05cb35e1d90fc37840d1)  You might have to pull the latest code.

**Comment by bgm13** [comment]
Thanks, just pulled the latest. Will monitor for the next match.

**Comment by ImDevinC** [comment]
Yep, already fixed!
