### ISSUE TITLE
[REQUEST] List of Daily Matches

### ISSUE THREAD

**Issue by jose-duarte** [ImDevinC/wc-watcher#26]
Hey, just noticed that in the fifa app for example it's easy to get a daily overview of the matches.
Any change we can export that from the API to slack as well?

Cheers.

**Comment by ImDevinC** [comment]
I've looked at this, but I can't find a good format to display this in. I have some more ideas, especially since we're about to go into the round of 16, maybe I'll take another crack at it.

**Comment by ImDevinC** [comment]
Resolved in the above commit. This prints at midnight to your local time, and shows all matches for the next 24 hours. Output can be seen below.

<img width="234" alt="screen shot 2018-06-25 at 11 05 48 pm" src="https://user-images.githubusercontent.com/3997333/41892278-538c50aa-78cc-11e8-8233-e88030d6bd68.png">
