### ISSUE TITLE
Missing event information is displayed every few minutes in the main channel

### ISSUE THREAD

**Issue by stardust20** [ImDevinC/wc-watcher#5]
When debug is set to **True**, I keep getting the following messages every 5 minutes approximately when nothing is happening in the game:

```
Missing event information for Egypt vs Uruguay: Event 20
https://api.fifa.com/api/v1/timelines/17/254645/275073/300353632?language=en-US
```

The messages are displayed in the main channel, shouldn't they be displayed in the debug channel?

**Comment by M4CC** [comment]
I have the same problem:

> Missing event information for Egypt vs Uruguay: Event 27
https://api.fifa.com/api/v1/timelines/17/254645/275073/300353632?language=en-US

Missing event information for Egypt vs Uruguay: Event 27
https://api.fifa.com/api/v1/timelines/17/254645/275073/300353632?language=en-US

**Comment by jose-duarte** [comment]
Same here
Missing event information for Egypt vs Uruguay: Event 30
https://api.fifa.com/api/v1/timelines/17/254645/275073/300353632?language=en-US

**Comment by omarrodriguez15** [comment]
I created a pull request with the ability to set a separate debug channel. If you set the CHANNEL and DEBUG_CHANNEL you can get away with using the same webhook for both WEBHOOK_URL and DEBUG_WEBHOOK.

**Comment by ImDevinC** [comment]
This is because debugging is enabled. In your private.py file, set `DEBUG = False` and this message won't be sent. As @omarrodriguez15 mentioned, a PR may come in to change where this message gets sent by default.

**Comment by ImDevinC** [comment]
I just updated the master branch with 293551 that now sends the missing event info to the debug channel if you have debug set to true

**Comment by stardust20** [comment]
By the way, how did you manage to get the information on the events? There's very little to guess in those responses you get from the FIFA API.
