### ISSUE TITLE
Wrong message for yellow cards

### ISSUE THREAD

**Issue by stardust20** [ImDevinC/wc-watcher#6]
The following message is posted when a booking happens:

```
:yellow_card_new: 90'+6' Yellow card.
> A. HEGAZY (Egypt)
```

It seems that the message is not processed correctly, so there's no proper message nor icon.

**Comment by elliottcarlson** [comment]
See https://github.com/ImDevinC/wc-watcher/pull/8 for icons and instructions

**Comment by stardust20** [comment]
I downloaded the icons from https://slackmojis.com by the way.
